# Generated by Django 5.1 on 2024-08-17 11:30

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_books_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('created', models.DateField(auto_created=datetime.datetime(2024, 8, 17, 11, 30, 26, 154520, tzinfo=datetime.timezone.utc))),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('genre', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='books',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='gener',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.genre'),
        ),
    ]
