# Generated by Django 5.1 on 2024-08-17 12:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_books_description_books_image_books_publication_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='created',
            field=models.DateField(auto_created=datetime.datetime(2024, 8, 17, 12, 26, 3, 223042, tzinfo=datetime.timezone.utc)),
        ),
    ]
