# Generated by Django 5.1 on 2024-08-24 11:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_books_image_alter_genre_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='modified_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='books',
            name='updated_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='created',
            field=models.DateField(auto_created=datetime.datetime(2024, 8, 24, 11, 14, 47, 408984, tzinfo=datetime.timezone.utc)),
        ),
    ]
