# Generated by Django 5.1 on 2024-08-24 11:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_books_modified_date_books_updated_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='modified_date',
        ),
        migrations.RemoveField(
            model_name='books',
            name='updated_by',
        ),
        migrations.AlterField(
            model_name='genre',
            name='created',
            field=models.DateField(auto_created=datetime.datetime(2024, 8, 24, 11, 20, 20, 916661, tzinfo=datetime.timezone.utc)),
        ),
    ]
