# Generated by Django 5.1 on 2024-08-24 11:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_books_modified_date_remove_books_updated_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='modified_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='books',
            name='updated_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='created',
            field=models.DateField(auto_created=datetime.datetime(2024, 8, 24, 11, 20, 58, 902674, tzinfo=datetime.timezone.utc)),
        ),
    ]
