# Generated by Django 5.1 on 2024-08-24 11:24

import datetime
import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_books_modified_date_books_updated_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='updated_by',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name=django.contrib.auth.models.User),
        ),
        migrations.AlterField(
            model_name='genre',
            name='created',
            field=models.DateField(auto_created=datetime.datetime(2024, 8, 24, 11, 24, 18, 233863, tzinfo=datetime.timezone.utc)),
        ),
    ]
