# Generated by Django 5.1 on 2024-08-24 11:25

import datetime
import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_books_updated_by_alter_genre_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='updated_by',
            field=models.CharField(blank=True, default=django.contrib.auth.models.User, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='created',
            field=models.DateField(auto_created=datetime.datetime(2024, 8, 24, 11, 25, 40, 640907, tzinfo=datetime.timezone.utc)),
        ),
    ]
