# Generated by Django 5.1 on 2024-08-25 11:13

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_books_updated_by_alter_genre_created'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='genre',
            name='created',
            field=models.DateField(auto_created=datetime.datetime(2024, 8, 25, 11, 13, 34, 4715, tzinfo=datetime.timezone.utc)),
        ),
    ]
