# Generated by Django 5.1 on 2024-08-25 11:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_books_updated_by_alter_genre_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='books',
            name='update_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='created',
            field=models.DateField(auto_created=datetime.datetime(2024, 8, 25, 11, 16, 49, 286672, tzinfo=datetime.timezone.utc)),
        ),
    ]
