# Generated by Django 5.1 on 2024-08-25 11:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_books_updated_by_books_update_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='create_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='created',
            field=models.DateField(auto_created=datetime.datetime(2024, 8, 25, 11, 20, 39, 629639, tzinfo=datetime.timezone.utc)),
        ),
    ]
