# Generated by Django 5.1 on 2024-08-25 11:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_books_create_by_alter_genre_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='created_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='created',
            field=models.DateField(auto_created=datetime.datetime(2024, 8, 25, 11, 24, 1, 564209, tzinfo=datetime.timezone.utc)),
        ),
    ]
