# Generated by Django 5.1 on 2024-08-25 11:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_books_created_date_alter_genre_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='modified_date',
            new_name='update_date',
        ),
        migrations.AlterField(
            model_name='genre',
            name='created',
            field=models.DateField(auto_created=datetime.datetime(2024, 8, 25, 11, 31, 6, 796590, tzinfo=datetime.timezone.utc)),
        ),
    ]
